<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0xjc4tA\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0xjc4tA/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0xjc4tA.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0xjc4tA\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container0xjc4tA\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '0xjc4tA',
    'container.build_id' => '715ff28c',
    'container.build_time' => 1685286949,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0xjc4tA');
