<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    'backoffice' => [[], ['_controller' => 'App\\Controller\\Admin\\BackOfficeController::index'], [], [['text', '/backoffice']], [], []],
    'backlogin' => [[], ['_controller' => 'App\\Controller\\Admin\\SecurityController::login'], [], [['text', '/backlogin']], [], []],
    'Animangas' => [[], ['_controller' => 'App\\Controller\\AnimangaController::index'], [], [['text', '/api/animangas']], [], []],
    'Top_Animangas' => [[], ['_controller' => 'App\\Controller\\AnimangaController::top'], [], [['text', '/api/animangas/top']], [], []],
    'Animangas_Names' => [[], ['_controller' => 'App\\Controller\\AnimangaController::names'], [], [['text', '/api/animangas/names']], [], []],
    'loginPage' => [[], ['_controller' => 'App\\Controller\\LoginController::login'], [], [['text', '/login']], [], []],
    'homePage' => [[], ['_controller' => 'App\\Controller\\MainController::homepage'], [], [['text', '/']], [], []],
    'searchAnimanga' => [['slug'], ['slug' => null, '_controller' => 'App\\Controller\\MainController::search'], [], [['variable', '/', '[^/]++', 'slug'], ['text', '/search']], [], []],
    'genreAnimanga' => [['slug'], ['slug' => null, '_controller' => 'App\\Controller\\MainController::browse'], [], [['variable', '/', '[^/]++', 'slug'], ['text', '/browse']], [], []],
    'genreManga' => [['slug'], ['slug' => null, '_controller' => 'App\\Controller\\MainController::browseManga'], [], [['variable', '/', '[^/]++', 'slug'], ['text', '/browseManga']], [], []],
    'genreAnime' => [['slug'], ['slug' => null, '_controller' => 'App\\Controller\\MainController::browseAnime'], [], [['variable', '/', '[^/]++', 'slug'], ['text', '/browseAnime']], [], []],
    'animanga' => [['slug'], ['slug' => null, '_controller' => 'App\\Controller\\MainController::animanga'], [], [['variable', '/', '[^/]++', 'slug'], ['text', '/animanga']], [], []],
    'genreRandom' => [[], ['_controller' => 'App\\Controller\\MainController::genreRandom'], [], [['text', '/random']], [], []],
    'users' => [['id'], ['id' => null, '_controller' => 'App\\Controller\\MainController::userProfil'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/users']], [], []],
    'app.swagger_ui' => [[], ['_controller' => 'nelmio_api_doc.controller.swagger_ui'], [], [['text', '/api/doc']], [], []],
];
